### ISSUE TITLE
Backup fail

### ISSUE THREAD

**Issue by Andor-py** [Sitois/Nuclear-V2#15]
I wanted to copy a server and with a little fiddling everything worked but all the roles are without permission and are in reverse order than on the original server (the first is deniet and the last is first) I just wanted to point out this little bug because with all the big ones we could have missed it.

Good luck                                                              **:** *)*

**Comment by Sitois** [comment]
That's why v1.8 is called a "developement version"...
Please don't open Issue for a developmeent version bug
