### ISSUE TITLE
How do I use this tool?

### ISSUE THREAD

**Issue by Futuraura** [Sitois/Nuclear-V2#3]
Tried sending ?help in dms and on a server that bot and I are on, nothing works.
The tutorial is not clear on usage at all. The bot does show custom RPC, but as I said earlier no signs of life when entering commands.

**Comment by Futuraura** [comment]
Oh, and also, the guilded link doesn't work.

**Comment by Sitois** [comment]
idk what guilded did

**Comment by Sitois** [comment]
> Tried sending ?help in dms and on a server that bot and I are on, nothing works. The tutorial is not clear on usage at all. The bot does show custom RPC, but as I said earlier no signs of life when entering commands.

um default prefix is &

**Comment by Futuraura** [comment]
> idk what guilded did

Can you make it so that another user cpuld use the selfbot too and enter allowed users ids in config

**Comment by Sitois** [comment]
> > idk what guilded did
> 
> Can you make it so that another user cpuld use the selfbot too and enter allowed users ids in config

yes it's in my TODO.md

So, the selfbot work for you ?

**Comment by Futuraura** [comment]
> > > idk what guilded did
> > 
> > Can you make it so that another user cpuld use the selfbot too and enter allowed users ids in config
> 
> yes it's in my TODO.md
> 
> So, the selfbot work for you ?

Yeah, but it was really confusing in the part of how to use it because it's not said anywhere that you have to message from the bot account itself. I suggest you add that to ReadMe.md

**Comment by Sitois** [comment]
fixed guilded weird thing

**Comment by Sitois** [comment]
so i answered all of your question ? I can close the issue ?

**Comment by Sitois** [comment]
@Futuraura

**Comment by Futuraura** [comment]
Thanks for replying and being helpful!

**Comment by a2hg** [comment]
getting an error @Sitois 
Traceback (most recent call last):
  File "c:\Users\dn5x\Downloads\Nuclear\Nuclear\main.py", line 31, in <module>
    from commands import *
  File "c:\Users\dn5x\Downloads\Nuclear\Nuclear\commands\__init__.py", line 1, in <module>
    from .help import HelpCommands
  File "c:\Users\dn5x\Downloads\Nuclear\Nuclear\commands\help.py", line 1, in <module>
    import discord
  File "C:\Users\dn5x\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\__init__.py", line 22, in <module>
    from . import abc as abc, opus as opus, utils as utils
  File "C:\Users\dn5x\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\abc.py", line 63, in <module>
    from .commands import ApplicationCommand, BaseCommand, SlashCommand, UserCommand, MessageCommand, _command_factory
  File "C:\Users\dn5x\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\commands\__init__.py", line 26, in <module>
    from .context import *
  File "C:\Users\dn5x\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\commands\context.py", line 30, in <module>
    from discord.interactions import Interaction, InteractionMessage, InteractionResponse
ImportError: cannot import name 'InteractionMessage' from 'discord.interactions' (C:\Users\dn5x\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\interactions.py). Did you mean: 'InteractionType'?

**Comment by Sitois** [comment]
> getting an error @Sitois 
> Traceback (most recent call last):
>   File "c:\Users\dn5x\Downloads\Nuclear\Nuclear\main.py", line 31, in <module>
>     from commands import *
>   File "c:\Users\dn5x\Downloads\Nuclear\Nuclear\commands\__init__.py", line 1, in <module>
>     from .help import HelpCommands
>   File "c:\Users\dn5x\Downloads\Nuclear\Nuclear\commands\help.py", line 1, in <module>
>     import discord
>   File "C:\Users\dn5x\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\__init__.py", line 22, in <module>
>     from . import abc as abc, opus as opus, utils as utils
>   File "C:\Users\dn5x\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\abc.py", line 63, in <module>
>     from .commands import ApplicationCommand, BaseCommand, SlashCommand, UserCommand, MessageCommand, _command_factory
>   File "C:\Users\dn5x\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\commands\__init__.py", line 26, in <module>
>     from .context import *
>   File "C:\Users\dn5x\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\commands\context.py", line 30, in <module>
>     from discord.interactions import Interaction, InteractionMessage, InteractionResponse
> ImportError: cannot import name 'InteractionMessage' from 'discord.interactions' (C:\Users\dn5x\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\interactions.py). Did you mean: 'InteractionType'?

Did u installed the discord library with git ?

`pip uninstall discord discord.py-self discord.py nextcord pycord py-cord`

And re-install discord.py-self
